name: Wyndmyll Creations
favicon: null
layout_spectrum: 0.50389
typography_spectrum: 0.74812
title: Aerial Photography & Videography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000400'
    - '#02f9fe'
    - '#02aad1'
    - '#675a05'
  brandStrength: 0.8125
  lightness: 0.31376652931794524
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
