name: wyndmyllcreations.com
favicon: null
layout_spectrum: 0.08474377170205116
typography_spectrum: 0.384966402547434
title: 'Aerial Photography & Videography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4706016869749874
  lightness: 0.31376652931794524
  saturation: 0.5861040728632361
  rhythmicContrast: 0.7116668524686247
purpose: []
